### ISSUE TITLE
Colors not matching the preview screenshot

### ISSUE THREAD

**Issue by Hnri** [aliou/moriarty.vim#3]
I love how the colorscheme looks but when I installed it `:colorscheme moriarty` the background and all the other colors where a little bit off (I'm using iTerm 2 and I did set &t_Co to 256).
Do you use an actual GUI or github is rendering the colors weirdly ?

**Comment by aliou** [comment]
Sorry to reply so late, I just saw this. The screenshot is made with iTerm 2 and CLI vim, so not sure what the problem is.
Do you think you could update a screenshot of what you are seeing? Thanks!

**Comment by Hnri** [comment]
Here's a screenshot: 
![screen shot 2016-07-26 at 14 17 36](https://cloud.githubusercontent.com/assets/18141469/17137517/d01a196c-533b-11e6-930c-54d070f87ed1.png)

I used OS X's digital Color Meter to compare the backgrounds and mine was (21,21,20) and the one on the readme was (18,18,18).
According to me the issue could be due to different Display Profiles (System Preferences -> Displays -> Color). 
We won't be able to fix it by changing the .vim file

**Comment by aliou** [comment]
I also use an iTerm profile with custom colours, not sure if this is related:

<img width="1030" alt="screen shot 2016-07-26 at 15 15 20" src="https://cloud.githubusercontent.com/assets/980367/17139208/c90952a2-5343-11e6-9721-56def3d17374.png">

**Comment by aliou** [comment]
(You can find the colours here: [gist](https://gist.github.com/aliou/ec2d56a017b59b99b52cf5bbe818fdd5))

**Comment by Hnri** [comment]
I hate to give up, but it seems rather hard to try and mess with the color profiles to solve this issue.
The theme looks good anyways.

**Comment by aliou** [comment]
I understand. Thanks 👍
